// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jthcgindzirgvirksqla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0aGNnaW5kemlyZ3ZpcmtzcWxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzIzNzgsImV4cCI6MjA2OTkwODM3OH0.OZ5BRTUJb-v6xR6_12b9SYZuGji1o-Vg7uqRs1ToeVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});